name: "Run SBOM scripts"
description: "Scan the current container for an SBOM, and check it for security issues."
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run SBOM scan
      run: entrypoint.sh
      shell: bash

    - name: Upload SBOM artifacts
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
      with:
        name: sbom-files
        path: "**/*sbom-*.json"
