# action.yml
name: 'EPS SBOM'
description: 'Create SBOMs, and scan for security risks.'
inputs:
  node_version:
    description: 'Node.js version to use'
    required: true
  cyclone_python_version:
    description: 'CycloneDX Python version to use'
    default: '4.5.0'
    required: false
  cyclone_npm_version:
    description: 'CycloneDX NPM version to use'
    default: '1.19.3'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - NODE_VERSION=${{ inputs.node_version }}
    - CYCLONE_PYTHON_VERSION=${{ inputs.cyclone_python_version }}
    - CYCLONE_NPM_VERSION=${{ inputs.cyclone_npm_version }}
