name: 'SBOM Generation and Security Scanning'

on:
  workflow_call:

jobs:
  sbom_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}
          fetch-depth: 0

      - name: Build and run Dev Container
        uses: devcontainers/ci@v0.3
        with:
          runCmd:  |
            # Download the SBOM scan script
            curl -sSfL https://raw.githubusercontent.com/NHSDigital/eps-action-sbom/refs/heads/aea-0000-move-to-syft/run-sbom-scan.sh -o run-sbom-scan.sh
            chmod +x ./run-sbom-scan.sh

            # Execute the script
            ./run-sbom-scan.sh
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}